/*
 * This file was automatically generated by EvoSuite
 * Fri Mar 02 19:47:31 GMT 2018
 */

package almoxarifadovirtual.servidor.excecoes;

import org.junit.Test;
import static org.junit.Assert.*;
import almoxarifadovirtual.servidor.excecoes.ProdutoInsuficienteException;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class ProdutoInsuficienteException_ESTest extends ProdutoInsuficienteException_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      ProdutoInsuficienteException produtoInsuficienteException0 = new ProdutoInsuficienteException();
  }
}
