/*
 * This file was automatically generated by EvoSuite
 * Sat Nov 18 14:19:49 GMT 2017
 */

package lesufcg.almoxarifadovirtual;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.shaded.org.mockito.Mockito.*;
import static org.evosuite.runtime.MockitoExtension.*;
import java.util.List;
import lesufcg.almoxarifadovirtual.AvirtualFachada;
import lesufcg.almoxarifadovirtual.controle.Controle;
import lesufcg.almoxarifadovirtual.modelo.usuario.Usuario;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.evosuite.runtime.ViolatedAssumptionAnswer;
import org.evosuite.runtime.javaee.injection.Injector;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class AvirtualFachada_ESTest extends AvirtualFachada_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      AvirtualFachada avirtualFachada0 = new AvirtualFachada();
      Usuario usuario0 = mock(Usuario.class, new ViolatedAssumptionAnswer());
      doReturn((String) null).when(usuario0).toString();
      Controle controle0 = mock(Controle.class, new ViolatedAssumptionAnswer());
      doReturn(true).when(controle0).atualizarUsuario(any(lesufcg.almoxarifadovirtual.modelo.usuario.Usuario.class));
      doReturn(usuario0).when(controle0).getUsuario(anyLong());
      Injector.inject(avirtualFachada0, (Class<?>) AvirtualFachada.class, "controle", (Object) controle0);
      Injector.validateBean(avirtualFachada0, (Class<?>) AvirtualFachada.class);
      Long long0 = new Long((-1634L));
      Usuario usuario1 = avirtualFachada0.getUsuario(long0);
      boolean boolean0 = avirtualFachada0.update(usuario1);
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      AvirtualFachada avirtualFachada0 = new AvirtualFachada();
      Controle controle0 = mock(Controle.class, new ViolatedAssumptionAnswer());
      doReturn((List) null).when(controle0).getUsuarioByFuncao(any(lesufcg.almoxarifadovirtual.modelo.usuario.FuncaoUsuario.class));
      Injector.inject(avirtualFachada0, (Class<?>) AvirtualFachada.class, "controle", (Object) controle0);
      Injector.validateBean(avirtualFachada0, (Class<?>) AvirtualFachada.class);
      List<Usuario> list0 = avirtualFachada0.listarPrestadores();
      assertNull(list0);
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      AvirtualFachada avirtualFachada0 = new AvirtualFachada();
      Controle controle0 = mock(Controle.class, new ViolatedAssumptionAnswer());
      doReturn((List) null).when(controle0).getUsuarioByFuncao(any(lesufcg.almoxarifadovirtual.modelo.usuario.FuncaoUsuario.class));
      Injector.inject(avirtualFachada0, (Class<?>) AvirtualFachada.class, "controle", (Object) controle0);
      Injector.validateBean(avirtualFachada0, (Class<?>) AvirtualFachada.class);
      List<Usuario> list0 = avirtualFachada0.listarAlmoxarifes();
      assertNull(list0);
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      AvirtualFachada avirtualFachada0 = new AvirtualFachada();
      Controle controle0 = mock(Controle.class, new ViolatedAssumptionAnswer());
      doReturn((List) null).when(controle0).getUsuarioByFuncao(any(lesufcg.almoxarifadovirtual.modelo.usuario.FuncaoUsuario.class));
      Injector.inject(avirtualFachada0, (Class<?>) AvirtualFachada.class, "controle", (Object) controle0);
      Injector.validateBean(avirtualFachada0, (Class<?>) AvirtualFachada.class);
      List<Usuario> list0 = avirtualFachada0.listarAdministradores();
      assertNull(list0);
  }

  @Test(timeout = 4000)
  public void test4()  throws Throwable  {
      AvirtualFachada avirtualFachada0 = new AvirtualFachada();
      Controle controle0 = mock(Controle.class, new ViolatedAssumptionAnswer());
      doReturn((List) null).when(controle0).getAllUsuarios();
      Injector.inject(avirtualFachada0, (Class<?>) AvirtualFachada.class, "controle", (Object) controle0);
      Injector.validateBean(avirtualFachada0, (Class<?>) AvirtualFachada.class);
      List<Usuario> list0 = avirtualFachada0.getAll();
      assertNull(list0);
  }

  @Test(timeout = 4000)
  public void test5()  throws Throwable  {
      AvirtualFachada avirtualFachada0 = new AvirtualFachada();
      Usuario usuario0 = mock(Usuario.class, new ViolatedAssumptionAnswer());
      doReturn((String) null).when(usuario0).toString();
      Controle controle0 = mock(Controle.class, new ViolatedAssumptionAnswer());
      doReturn(usuario0).when(controle0).criarUsuario(any(lesufcg.almoxarifadovirtual.modelo.usuario.Usuario.class));
      Injector.inject(avirtualFachada0, (Class<?>) AvirtualFachada.class, "controle", (Object) controle0);
      Injector.validateBean(avirtualFachada0, (Class<?>) AvirtualFachada.class);
      Usuario usuario1 = avirtualFachada0.criarUsuario((Usuario) null);
      assertSame(usuario1, usuario0);
  }

  @Test(timeout = 4000)
  public void test6()  throws Throwable  {
      AvirtualFachada avirtualFachada0 = new AvirtualFachada();
      Controle controle0 = mock(Controle.class, new ViolatedAssumptionAnswer());
      doReturn((Usuario) null).when(controle0).getUsuario(anyLong());
      Injector.inject(avirtualFachada0, (Class<?>) AvirtualFachada.class, "controle", (Object) controle0);
      Injector.validateBean(avirtualFachada0, (Class<?>) AvirtualFachada.class);
      Usuario usuario0 = avirtualFachada0.getUsuario((Long) null);
      assertNull(usuario0);
  }

  @Test(timeout = 4000)
  public void test7()  throws Throwable  {
      AvirtualFachada avirtualFachada0 = new AvirtualFachada();
      Controle controle0 = mock(Controle.class, new ViolatedAssumptionAnswer());
      doReturn(false).when(controle0).deletarUsuario(anyLong());
      Injector.inject(avirtualFachada0, (Class<?>) AvirtualFachada.class, "controle", (Object) controle0);
      Injector.validateBean(avirtualFachada0, (Class<?>) AvirtualFachada.class);
      avirtualFachada0.delete((Long) null);
  }

  @Test(timeout = 4000)
  public void test8()  throws Throwable  {
      AvirtualFachada avirtualFachada0 = new AvirtualFachada();
      Controle controle0 = mock(Controle.class, new ViolatedAssumptionAnswer());
      doReturn(false).when(controle0).atualizarUsuario(any(lesufcg.almoxarifadovirtual.modelo.usuario.Usuario.class));
      Injector.inject(avirtualFachada0, (Class<?>) AvirtualFachada.class, "controle", (Object) controle0);
      Injector.validateBean(avirtualFachada0, (Class<?>) AvirtualFachada.class);
      boolean boolean0 = avirtualFachada0.update((Usuario) null);
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test9()  throws Throwable  {
      AvirtualFachada avirtualFachada0 = new AvirtualFachada();
      Controle controle0 = mock(Controle.class, new ViolatedAssumptionAnswer());
      doReturn((Usuario) null).when(controle0).criarUsuario(any(lesufcg.almoxarifadovirtual.modelo.usuario.Usuario.class));
      Injector.inject(avirtualFachada0, (Class<?>) AvirtualFachada.class, "controle", (Object) controle0);
      Injector.validateBean(avirtualFachada0, (Class<?>) AvirtualFachada.class);
      Usuario usuario0 = avirtualFachada0.criarUsuario((Usuario) null);
      assertNull(usuario0);
  }
}
