/*
 * This file was automatically generated by EvoSuite
 * Fri Mar 02 19:48:22 GMT 2018
 */

package almoxarifadovirtual.servidor;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import almoxarifadovirtual.servidor.AvirtualApplication;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class AvirtualApplication_ESTest extends AvirtualApplication_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      String[] stringArray0 = new String[5];
      stringArray0[0] = "]Q#:;~J}O`-Q6*q";
      stringArray0[1] = "";
      stringArray0[2] = "2}_mYoYqDo|)e";
      stringArray0[3] = "";
      stringArray0[4] = "_k:[!-]:Qxe}w";
      // Undeclared exception!
      AvirtualApplication.main(stringArray0);
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      AvirtualApplication avirtualApplication0 = new AvirtualApplication();
  }
}
