/**
 * Scaffolding file used to store all the setups needed to run 
 * tests automatically generated by EvoSuite
 * Fri Mar 02 19:38:45 GMT 2018
 */

package almoxarifadovirtual.servidor.controle;

import org.evosuite.runtime.annotation.EvoSuiteClassExclude;
import org.junit.BeforeClass;
import org.junit.Before;
import org.junit.After;
import org.junit.AfterClass;
import org.evosuite.runtime.sandbox.Sandbox;
import org.evosuite.runtime.sandbox.Sandbox.SandboxMode;

import static org.evosuite.shaded.org.mockito.Mockito.*;
@EvoSuiteClassExclude
public class ControleDeAcesso_ESTest_scaffolding {

  @org.junit.Rule 
  public org.evosuite.runtime.vnet.NonFunctionalRequirementRule nfr = new org.evosuite.runtime.vnet.NonFunctionalRequirementRule();

  private static final java.util.Properties defaultProperties = (java.util.Properties) java.lang.System.getProperties().clone(); 

  private org.evosuite.runtime.thread.ThreadStopper threadStopper =  new org.evosuite.runtime.thread.ThreadStopper (org.evosuite.runtime.thread.KillSwitchHandler.getInstance(), 3000);


  @BeforeClass 
  public static void initEvoSuiteFramework() { 
    org.evosuite.runtime.RuntimeSettings.className = "almoxarifadovirtual.servidor.controle.ControleDeAcesso"; 
    org.evosuite.runtime.GuiSupport.initialize(); 
    org.evosuite.runtime.RuntimeSettings.maxNumberOfThreads = 100; 
    org.evosuite.runtime.RuntimeSettings.maxNumberOfIterationsPerLoop = 10000; 
    org.evosuite.runtime.RuntimeSettings.mockSystemIn = true; 
    org.evosuite.runtime.RuntimeSettings.sandboxMode = org.evosuite.runtime.sandbox.Sandbox.SandboxMode.RECOMMENDED; 
    org.evosuite.runtime.sandbox.Sandbox.initializeSecurityManagerForSUT(); 
    org.evosuite.runtime.classhandling.JDKClassResetter.init();
    setSystemProperties();
    initializeClasses();
    org.evosuite.runtime.Runtime.getInstance().resetRuntime(); 
    try { initMocksToAvoidTimeoutsInTheTests(); } catch(ClassNotFoundException e) {} 
  } 

  @AfterClass 
  public static void clearEvoSuiteFramework(){ 
    Sandbox.resetDefaultSecurityManager(); 
    java.lang.System.setProperties((java.util.Properties) defaultProperties.clone()); 
  } 

  @Before 
  public void initTestCase(){ 
    threadStopper.storeCurrentThreads();
    threadStopper.startRecordingTime();
    org.evosuite.runtime.jvm.ShutdownHookHandler.getInstance().initHandler(); 
    org.evosuite.runtime.sandbox.Sandbox.goingToExecuteSUTCode(); 
    setSystemProperties(); 
    org.evosuite.runtime.GuiSupport.setHeadless(); 
    org.evosuite.runtime.Runtime.getInstance().resetRuntime(); 
    org.evosuite.runtime.agent.InstrumentingAgent.activate(); 
  } 

  @After 
  public void doneWithTestCase(){ 
    threadStopper.killAndJoinClientThreads();
    org.evosuite.runtime.jvm.ShutdownHookHandler.getInstance().safeExecuteAddedHooks(); 
    org.evosuite.runtime.classhandling.JDKClassResetter.reset(); 
    resetClasses(); 
    org.evosuite.runtime.sandbox.Sandbox.doneWithExecutingSUTCode(); 
    org.evosuite.runtime.agent.InstrumentingAgent.deactivate(); 
    org.evosuite.runtime.GuiSupport.restoreHeadlessMode(); 
  } 

  public static void setSystemProperties() {
 
    java.lang.System.setProperties((java.util.Properties) defaultProperties.clone()); 
    java.lang.System.setProperty("file.encoding", "UTF-8"); 
    java.lang.System.setProperty("java.awt.headless", "true"); 
    java.lang.System.setProperty("user.country", "US"); 
    java.lang.System.setProperty("user.language", "en"); 
    java.lang.System.setProperty("user.timezone", "America/Recife"); 
  }

  private static void initializeClasses() {
    org.evosuite.runtime.classhandling.ClassStateSupport.initializeClasses(ControleDeAcesso_ESTest_scaffolding.class.getClassLoader() ,
      "almoxarifadovirtual.servidor.controle.Utils",
      "almoxarifadovirtual.servidor.excecoes.TokenException",
      "almoxarifadovirtual.servidor.controle.ControleDeAutenticacao",
      "org.springframework.beans.factory.annotation.Autowired",
      "almoxarifadovirtual.servidor.servico.ServicoLdap",
      "org.springframework.data.domain.Sort$Direction",
      "org.springframework.util.MimeType",
      "almoxarifadovirtual.servidor.modelo.usuario.FuncaoUsuario",
      "almoxarifadovirtual.servidor.servico.ServicoToken",
      "org.springframework.data.repository.Repository",
      "org.springframework.data.domain.Sort",
      "org.springframework.data.domain.Pageable",
      "org.springframework.stereotype.Repository",
      "almoxarifadovirtual.servidor.repositorio.RepositorioDeUsuario",
      "org.springframework.data.repository.PagingAndSortingRepository",
      "org.springframework.http.HttpHeaders",
      "org.springframework.http.MediaType",
      "org.springframework.web.bind.annotation.RequestMethod",
      "almoxarifadovirtual.servidor.controle.ControleDeAcesso",
      "org.springframework.data.domain.Page",
      "org.springframework.data.domain.Example",
      "org.springframework.web.bind.annotation.RestController",
      "org.springframework.data.domain.Slice",
      "org.springframework.http.HttpEntity",
      "org.springframework.util.CollectionUtils",
      "almoxarifadovirtual.servidor.excecoes.UsuarioException",
      "almoxarifadovirtual.servidor.servico.ServicoUsuario",
      "org.springframework.http.ResponseEntity$HeadersBuilder",
      "org.springframework.data.jpa.repository.JpaRepository",
      "org.springframework.util.LinkedCaseInsensitiveMap",
      "org.springframework.http.HttpStatus$Series",
      "org.springframework.http.MediaType$1",
      "org.springframework.web.bind.annotation.RequestMapping",
      "org.springframework.stereotype.Controller",
      "org.springframework.http.ResponseEntity$BodyBuilder",
      "org.springframework.data.repository.CrudRepository",
      "org.springframework.data.repository.NoRepositoryBean",
      "almoxarifadovirtual.servidor.modelo.usuario.Usuario",
      "org.springframework.stereotype.Service",
      "org.springframework.util.MimeType$SpecificityComparator",
      "org.springframework.util.InvalidMimeTypeException",
      "org.springframework.validation.annotation.Validated",
      "almoxarifadovirtual.servidor.repositorio.RepositorioDeToken",
      "org.springframework.http.HttpMethod",
      "almoxarifadovirtual.servidor.modelo.autenticacao.Token",
      "org.springframework.util.MultiValueMap",
      "org.springframework.util.MimeTypeUtils",
      "org.springframework.web.bind.annotation.ResponseBody",
      "almoxarifadovirtual.servidor.excecoes.PermissaoException",
      "org.springframework.util.LinkedCaseInsensitiveMap$1",
      "org.springframework.data.repository.query.QueryByExampleExecutor",
      "org.springframework.http.HttpStatus",
      "org.springframework.http.InvalidMediaTypeException",
      "org.springframework.stereotype.Component",
      "org.springframework.http.ResponseEntity",
      "almoxarifadovirtual.servidor.modelo.autenticacao.Credenciais",
      "org.springframework.web.bind.annotation.Mapping",
      "org.springframework.util.Assert",
      "org.springframework.util.StringUtils"
    );
  } 
  private static void initMocksToAvoidTimeoutsInTheTests() throws ClassNotFoundException { 
    mock(Class.forName("almoxarifadovirtual.servidor.repositorio.RepositorioDeToken", false, ControleDeAcesso_ESTest_scaffolding.class.getClassLoader()));
    mock(Class.forName("almoxarifadovirtual.servidor.repositorio.RepositorioDeUsuario", false, ControleDeAcesso_ESTest_scaffolding.class.getClassLoader()));
  }

  private static void resetClasses() {
    org.evosuite.runtime.classhandling.ClassResetter.getInstance().setClassLoader(ControleDeAcesso_ESTest_scaffolding.class.getClassLoader()); 

    org.evosuite.runtime.classhandling.ClassStateSupport.resetClasses(
      "org.springframework.http.HttpStatus",
      "almoxarifadovirtual.servidor.excecoes.TokenException",
      "almoxarifadovirtual.servidor.modelo.autenticacao.Token",
      "almoxarifadovirtual.servidor.excecoes.UsuarioException",
      "almoxarifadovirtual.servidor.excecoes.PermissaoException",
      "org.springframework.http.HttpHeaders",
      "org.springframework.util.LinkedCaseInsensitiveMap",
      "org.springframework.util.LinkedCaseInsensitiveMap$1",
      "org.springframework.http.HttpEntity"
    );
  }
}
