/*
 * This file was automatically generated by EvoSuite
 * Fri Mar 02 19:34:48 GMT 2018
 */

package almoxarifadovirtual.servidor.controle;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.shaded.org.mockito.Mockito.*;
import static org.evosuite.runtime.MockitoExtension.*;
import static org.evosuite.runtime.EvoAssertions.*;
import almoxarifadovirtual.servidor.controle.ControleDeAutenticacao;
import almoxarifadovirtual.servidor.controle.ControleDeProdutos;
import almoxarifadovirtual.servidor.modelo.autenticacao.Token;
import almoxarifadovirtual.servidor.modelo.produto.Produto;
import almoxarifadovirtual.servidor.repositorio.RepositorioDeOperacao;
import almoxarifadovirtual.servidor.repositorio.RepositorioDeProduto;
import almoxarifadovirtual.servidor.repositorio.RepositorioDeToken;
import almoxarifadovirtual.servidor.repositorio.RepositorioDeUsuario;
import almoxarifadovirtual.servidor.servico.ServicoDeOperacao;
import almoxarifadovirtual.servidor.servico.ServicoDeProduto;
import almoxarifadovirtual.servidor.servico.ServicoLdap;
import almoxarifadovirtual.servidor.servico.ServicoToken;
import almoxarifadovirtual.servidor.servico.ServicoUsuario;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.evosuite.runtime.ViolatedAssumptionAnswer;
import org.evosuite.runtime.javaee.injection.Injector;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class ControleDeProdutos_ESTest extends ControleDeProdutos_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      ControleDeProdutos controleDeProdutos0 = new ControleDeProdutos();
      ControleDeAutenticacao controleDeAutenticacao0 = new ControleDeAutenticacao();
      ServicoLdap servicoLdap0 = new ServicoLdap();
      Injector.inject(controleDeAutenticacao0, (Class<?>) ControleDeAutenticacao.class, "servicoLdap", (Object) servicoLdap0);
      ServicoToken servicoToken0 = new ServicoToken();
      RepositorioDeToken repositorioDeToken0 = mock(RepositorioDeToken.class, new ViolatedAssumptionAnswer());
      doReturn((Token) null).when(repositorioDeToken0).findByChave(anyString());
      Injector.inject(servicoToken0, (Class<?>) ServicoToken.class, "repository", (Object) repositorioDeToken0);
      Injector.validateBean(servicoToken0, (Class<?>) ServicoToken.class);
      Injector.inject(controleDeAutenticacao0, (Class<?>) ControleDeAutenticacao.class, "servicoToken", (Object) servicoToken0);
      ServicoUsuario servicoUsuario0 = new ServicoUsuario();
      RepositorioDeUsuario repositorioDeUsuario0 = mock(RepositorioDeUsuario.class, new ViolatedAssumptionAnswer());
      Injector.inject(servicoUsuario0, (Class<?>) ServicoUsuario.class, "repositorio", (Object) repositorioDeUsuario0);
      Injector.validateBean(servicoUsuario0, (Class<?>) ServicoUsuario.class);
      Injector.inject(controleDeAutenticacao0, (Class<?>) ControleDeAutenticacao.class, "servicoUsuario", (Object) servicoUsuario0);
      Injector.validateBean(controleDeAutenticacao0, (Class<?>) ControleDeAutenticacao.class);
      Injector.inject(controleDeProdutos0, (Class<?>) ControleDeProdutos.class, "controleDeAutenticacao", (Object) controleDeAutenticacao0);
      ServicoDeOperacao servicoDeOperacao0 = new ServicoDeOperacao();
      RepositorioDeOperacao repositorioDeOperacao0 = mock(RepositorioDeOperacao.class, new ViolatedAssumptionAnswer());
      Injector.inject(servicoDeOperacao0, (Class<?>) ServicoDeOperacao.class, "repositorioDeOperacao", (Object) repositorioDeOperacao0);
      Injector.validateBean(servicoDeOperacao0, (Class<?>) ServicoDeOperacao.class);
      Injector.inject(controleDeProdutos0, (Class<?>) ControleDeProdutos.class, "servicoDeOperacao", (Object) servicoDeOperacao0);
      ServicoDeProduto servicoDeProduto0 = new ServicoDeProduto();
      RepositorioDeProduto repositorioDeProduto0 = mock(RepositorioDeProduto.class, new ViolatedAssumptionAnswer());
      Injector.inject(servicoDeProduto0, (Class<?>) ServicoDeProduto.class, "repositorioDeProduto", (Object) repositorioDeProduto0);
      Injector.validateBean(servicoDeProduto0, (Class<?>) ServicoDeProduto.class);
      Injector.inject(controleDeProdutos0, (Class<?>) ControleDeProdutos.class, "servicoDeProduto", (Object) servicoDeProduto0);
      Injector.validateBean(controleDeProdutos0, (Class<?>) ControleDeProdutos.class);
      Long long0 = new Long((-1514L));
      // Undeclared exception!
      try { 
        controleDeProdutos0.retirarProduto(long0, (-1514L), "");
        fail("Expecting exception: RuntimeException");
      
      } catch(RuntimeException e) {
         //
         // Token inv\u00E1lido!
         //
         verifyException("almoxarifadovirtual.servidor.controle.ControleDeAutenticacao", e);
      }
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      ControleDeProdutos controleDeProdutos0 = new ControleDeProdutos();
      ControleDeAutenticacao controleDeAutenticacao0 = new ControleDeAutenticacao();
      ServicoLdap servicoLdap0 = new ServicoLdap();
      Injector.inject(controleDeAutenticacao0, (Class<?>) ControleDeAutenticacao.class, "servicoLdap", (Object) servicoLdap0);
      ServicoToken servicoToken0 = new ServicoToken();
      Token token0 = new Token();
      RepositorioDeToken repositorioDeToken0 = mock(RepositorioDeToken.class, new ViolatedAssumptionAnswer());
      doReturn(token0).when(repositorioDeToken0).findByChave(anyString());
      Injector.inject(servicoToken0, (Class<?>) ServicoToken.class, "repository", (Object) repositorioDeToken0);
      Injector.validateBean(servicoToken0, (Class<?>) ServicoToken.class);
      Injector.inject(controleDeAutenticacao0, (Class<?>) ControleDeAutenticacao.class, "servicoToken", (Object) servicoToken0);
      ServicoUsuario servicoUsuario0 = new ServicoUsuario();
      RepositorioDeUsuario repositorioDeUsuario0 = mock(RepositorioDeUsuario.class, new ViolatedAssumptionAnswer());
      Injector.inject(servicoUsuario0, (Class<?>) ServicoUsuario.class, "repositorio", (Object) repositorioDeUsuario0);
      Injector.validateBean(servicoUsuario0, (Class<?>) ServicoUsuario.class);
      Injector.inject(controleDeAutenticacao0, (Class<?>) ControleDeAutenticacao.class, "servicoUsuario", (Object) servicoUsuario0);
      Injector.validateBean(controleDeAutenticacao0, (Class<?>) ControleDeAutenticacao.class);
      Injector.inject(controleDeProdutos0, (Class<?>) ControleDeProdutos.class, "controleDeAutenticacao", (Object) controleDeAutenticacao0);
      ServicoDeOperacao servicoDeOperacao0 = new ServicoDeOperacao();
      RepositorioDeOperacao repositorioDeOperacao0 = mock(RepositorioDeOperacao.class, new ViolatedAssumptionAnswer());
      Injector.inject(servicoDeOperacao0, (Class<?>) ServicoDeOperacao.class, "repositorioDeOperacao", (Object) repositorioDeOperacao0);
      Injector.validateBean(servicoDeOperacao0, (Class<?>) ServicoDeOperacao.class);
      Injector.inject(controleDeProdutos0, (Class<?>) ControleDeProdutos.class, "servicoDeOperacao", (Object) servicoDeOperacao0);
      ServicoDeProduto servicoDeProduto0 = new ServicoDeProduto();
      RepositorioDeProduto repositorioDeProduto0 = mock(RepositorioDeProduto.class, new ViolatedAssumptionAnswer());
      Injector.inject(servicoDeProduto0, (Class<?>) ServicoDeProduto.class, "repositorioDeProduto", (Object) repositorioDeProduto0);
      Injector.validateBean(servicoDeProduto0, (Class<?>) ServicoDeProduto.class);
      Injector.inject(controleDeProdutos0, (Class<?>) ControleDeProdutos.class, "servicoDeProduto", (Object) servicoDeProduto0);
      Injector.validateBean(controleDeProdutos0, (Class<?>) ControleDeProdutos.class);
      Long long0 = new Long(0L);
      // Undeclared exception!
      try { 
        controleDeProdutos0.retirarProduto(long0, 0.0, "pRt");
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("almoxarifadovirtual.servidor.modelo.autenticacao.Token", e);
      }
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      ControleDeProdutos controleDeProdutos0 = new ControleDeProdutos();
      ControleDeAutenticacao controleDeAutenticacao0 = new ControleDeAutenticacao();
      ServicoLdap servicoLdap0 = new ServicoLdap();
      Injector.inject(controleDeAutenticacao0, (Class<?>) ControleDeAutenticacao.class, "servicoLdap", (Object) servicoLdap0);
      ServicoToken servicoToken0 = new ServicoToken();
      RepositorioDeToken repositorioDeToken0 = mock(RepositorioDeToken.class, new ViolatedAssumptionAnswer());
      doReturn((Token) null).when(repositorioDeToken0).findByChave(anyString());
      Injector.inject(servicoToken0, (Class<?>) ServicoToken.class, "repository", (Object) repositorioDeToken0);
      Injector.validateBean(servicoToken0, (Class<?>) ServicoToken.class);
      Injector.inject(controleDeAutenticacao0, (Class<?>) ControleDeAutenticacao.class, "servicoToken", (Object) servicoToken0);
      ServicoUsuario servicoUsuario0 = new ServicoUsuario();
      RepositorioDeUsuario repositorioDeUsuario0 = mock(RepositorioDeUsuario.class, new ViolatedAssumptionAnswer());
      Injector.inject(servicoUsuario0, (Class<?>) ServicoUsuario.class, "repositorio", (Object) repositorioDeUsuario0);
      Injector.validateBean(servicoUsuario0, (Class<?>) ServicoUsuario.class);
      Injector.inject(controleDeAutenticacao0, (Class<?>) ControleDeAutenticacao.class, "servicoUsuario", (Object) servicoUsuario0);
      Injector.validateBean(controleDeAutenticacao0, (Class<?>) ControleDeAutenticacao.class);
      Injector.inject(controleDeProdutos0, (Class<?>) ControleDeProdutos.class, "controleDeAutenticacao", (Object) controleDeAutenticacao0);
      ServicoDeOperacao servicoDeOperacao0 = new ServicoDeOperacao();
      RepositorioDeOperacao repositorioDeOperacao0 = mock(RepositorioDeOperacao.class, new ViolatedAssumptionAnswer());
      Injector.inject(servicoDeOperacao0, (Class<?>) ServicoDeOperacao.class, "repositorioDeOperacao", (Object) repositorioDeOperacao0);
      Injector.validateBean(servicoDeOperacao0, (Class<?>) ServicoDeOperacao.class);
      Injector.inject(controleDeProdutos0, (Class<?>) ControleDeProdutos.class, "servicoDeOperacao", (Object) servicoDeOperacao0);
      ServicoDeProduto servicoDeProduto0 = new ServicoDeProduto();
      RepositorioDeProduto repositorioDeProduto0 = mock(RepositorioDeProduto.class, new ViolatedAssumptionAnswer());
      Injector.inject(servicoDeProduto0, (Class<?>) ServicoDeProduto.class, "repositorioDeProduto", (Object) repositorioDeProduto0);
      Injector.validateBean(servicoDeProduto0, (Class<?>) ServicoDeProduto.class);
      Injector.inject(controleDeProdutos0, (Class<?>) ControleDeProdutos.class, "servicoDeProduto", (Object) servicoDeProduto0);
      Injector.validateBean(controleDeProdutos0, (Class<?>) ControleDeProdutos.class);
      Long long0 = new Long(0L);
      // Undeclared exception!
      try { 
        controleDeProdutos0.listarOperacoesPorUsuarioId(long0, "]Tnp2_:AE");
        fail("Expecting exception: RuntimeException");
      
      } catch(RuntimeException e) {
         //
         // Token inv\u00E1lido!
         //
         verifyException("almoxarifadovirtual.servidor.controle.ControleDeAutenticacao", e);
      }
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      ControleDeProdutos controleDeProdutos0 = new ControleDeProdutos();
      ControleDeAutenticacao controleDeAutenticacao0 = new ControleDeAutenticacao();
      ServicoLdap servicoLdap0 = new ServicoLdap();
      Injector.inject(controleDeAutenticacao0, (Class<?>) ControleDeAutenticacao.class, "servicoLdap", (Object) servicoLdap0);
      ServicoToken servicoToken0 = new ServicoToken();
      RepositorioDeToken repositorioDeToken0 = mock(RepositorioDeToken.class, new ViolatedAssumptionAnswer());
      doReturn((Token) null).when(repositorioDeToken0).findByChave(anyString());
      Injector.inject(servicoToken0, (Class<?>) ServicoToken.class, "repository", (Object) repositorioDeToken0);
      Injector.validateBean(servicoToken0, (Class<?>) ServicoToken.class);
      Injector.inject(controleDeAutenticacao0, (Class<?>) ControleDeAutenticacao.class, "servicoToken", (Object) servicoToken0);
      ServicoUsuario servicoUsuario0 = new ServicoUsuario();
      RepositorioDeUsuario repositorioDeUsuario0 = mock(RepositorioDeUsuario.class, new ViolatedAssumptionAnswer());
      Injector.inject(servicoUsuario0, (Class<?>) ServicoUsuario.class, "repositorio", (Object) repositorioDeUsuario0);
      Injector.validateBean(servicoUsuario0, (Class<?>) ServicoUsuario.class);
      Injector.inject(controleDeAutenticacao0, (Class<?>) ControleDeAutenticacao.class, "servicoUsuario", (Object) servicoUsuario0);
      Injector.validateBean(controleDeAutenticacao0, (Class<?>) ControleDeAutenticacao.class);
      Injector.inject(controleDeProdutos0, (Class<?>) ControleDeProdutos.class, "controleDeAutenticacao", (Object) controleDeAutenticacao0);
      ServicoDeOperacao servicoDeOperacao0 = new ServicoDeOperacao();
      RepositorioDeOperacao repositorioDeOperacao0 = mock(RepositorioDeOperacao.class, new ViolatedAssumptionAnswer());
      Injector.inject(servicoDeOperacao0, (Class<?>) ServicoDeOperacao.class, "repositorioDeOperacao", (Object) repositorioDeOperacao0);
      Injector.validateBean(servicoDeOperacao0, (Class<?>) ServicoDeOperacao.class);
      Injector.inject(controleDeProdutos0, (Class<?>) ControleDeProdutos.class, "servicoDeOperacao", (Object) servicoDeOperacao0);
      ServicoDeProduto servicoDeProduto0 = new ServicoDeProduto();
      RepositorioDeProduto repositorioDeProduto0 = mock(RepositorioDeProduto.class, new ViolatedAssumptionAnswer());
      Injector.inject(servicoDeProduto0, (Class<?>) ServicoDeProduto.class, "repositorioDeProduto", (Object) repositorioDeProduto0);
      Injector.validateBean(servicoDeProduto0, (Class<?>) ServicoDeProduto.class);
      Injector.inject(controleDeProdutos0, (Class<?>) ControleDeProdutos.class, "servicoDeProduto", (Object) servicoDeProduto0);
      Injector.validateBean(controleDeProdutos0, (Class<?>) ControleDeProdutos.class);
      // Undeclared exception!
      try { 
        controleDeProdutos0.listarOperacoesPorTipo("", "");
        fail("Expecting exception: RuntimeException");
      
      } catch(RuntimeException e) {
         //
         // Token inv\u00E1lido!
         //
         verifyException("almoxarifadovirtual.servidor.controle.ControleDeAutenticacao", e);
      }
  }

  @Test(timeout = 4000)
  public void test4()  throws Throwable  {
      ControleDeProdutos controleDeProdutos0 = new ControleDeProdutos();
      ControleDeAutenticacao controleDeAutenticacao0 = new ControleDeAutenticacao();
      ServicoLdap servicoLdap0 = new ServicoLdap();
      Injector.inject(controleDeAutenticacao0, (Class<?>) ControleDeAutenticacao.class, "servicoLdap", (Object) servicoLdap0);
      ServicoToken servicoToken0 = new ServicoToken();
      Token token0 = new Token();
      RepositorioDeToken repositorioDeToken0 = mock(RepositorioDeToken.class, new ViolatedAssumptionAnswer());
      doReturn(token0).when(repositorioDeToken0).findByChave(anyString());
      Injector.inject(servicoToken0, (Class<?>) ServicoToken.class, "repository", (Object) repositorioDeToken0);
      Injector.validateBean(servicoToken0, (Class<?>) ServicoToken.class);
      Injector.inject(controleDeAutenticacao0, (Class<?>) ControleDeAutenticacao.class, "servicoToken", (Object) servicoToken0);
      ServicoUsuario servicoUsuario0 = new ServicoUsuario();
      RepositorioDeUsuario repositorioDeUsuario0 = mock(RepositorioDeUsuario.class, new ViolatedAssumptionAnswer());
      Injector.inject(servicoUsuario0, (Class<?>) ServicoUsuario.class, "repositorio", (Object) repositorioDeUsuario0);
      Injector.validateBean(servicoUsuario0, (Class<?>) ServicoUsuario.class);
      Injector.inject(controleDeAutenticacao0, (Class<?>) ControleDeAutenticacao.class, "servicoUsuario", (Object) servicoUsuario0);
      Injector.validateBean(controleDeAutenticacao0, (Class<?>) ControleDeAutenticacao.class);
      Injector.inject(controleDeProdutos0, (Class<?>) ControleDeProdutos.class, "controleDeAutenticacao", (Object) controleDeAutenticacao0);
      ServicoDeOperacao servicoDeOperacao0 = new ServicoDeOperacao();
      RepositorioDeOperacao repositorioDeOperacao0 = mock(RepositorioDeOperacao.class, new ViolatedAssumptionAnswer());
      Injector.inject(servicoDeOperacao0, (Class<?>) ServicoDeOperacao.class, "repositorioDeOperacao", (Object) repositorioDeOperacao0);
      Injector.validateBean(servicoDeOperacao0, (Class<?>) ServicoDeOperacao.class);
      Injector.inject(controleDeProdutos0, (Class<?>) ControleDeProdutos.class, "servicoDeOperacao", (Object) servicoDeOperacao0);
      ServicoDeProduto servicoDeProduto0 = new ServicoDeProduto();
      RepositorioDeProduto repositorioDeProduto0 = mock(RepositorioDeProduto.class, new ViolatedAssumptionAnswer());
      Injector.inject(servicoDeProduto0, (Class<?>) ServicoDeProduto.class, "repositorioDeProduto", (Object) repositorioDeProduto0);
      Injector.validateBean(servicoDeProduto0, (Class<?>) ServicoDeProduto.class);
      Injector.inject(controleDeProdutos0, (Class<?>) ControleDeProdutos.class, "servicoDeProduto", (Object) servicoDeProduto0);
      Injector.validateBean(controleDeProdutos0, (Class<?>) ControleDeProdutos.class);
      // Undeclared exception!
      try { 
        controleDeProdutos0.listarOperacoesPorTipo("", "3");
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("almoxarifadovirtual.servidor.modelo.autenticacao.Token", e);
      }
  }

  @Test(timeout = 4000)
  public void test5()  throws Throwable  {
      ControleDeProdutos controleDeProdutos0 = new ControleDeProdutos();
      ControleDeAutenticacao controleDeAutenticacao0 = new ControleDeAutenticacao();
      ServicoLdap servicoLdap0 = new ServicoLdap();
      Injector.inject(controleDeAutenticacao0, (Class<?>) ControleDeAutenticacao.class, "servicoLdap", (Object) servicoLdap0);
      ServicoToken servicoToken0 = new ServicoToken();
      RepositorioDeToken repositorioDeToken0 = mock(RepositorioDeToken.class, new ViolatedAssumptionAnswer());
      doReturn((Token) null).when(repositorioDeToken0).findByChave(anyString());
      Injector.inject(servicoToken0, (Class<?>) ServicoToken.class, "repository", (Object) repositorioDeToken0);
      Injector.validateBean(servicoToken0, (Class<?>) ServicoToken.class);
      Injector.inject(controleDeAutenticacao0, (Class<?>) ControleDeAutenticacao.class, "servicoToken", (Object) servicoToken0);
      ServicoUsuario servicoUsuario0 = new ServicoUsuario();
      RepositorioDeUsuario repositorioDeUsuario0 = mock(RepositorioDeUsuario.class, new ViolatedAssumptionAnswer());
      Injector.inject(servicoUsuario0, (Class<?>) ServicoUsuario.class, "repositorio", (Object) repositorioDeUsuario0);
      Injector.validateBean(servicoUsuario0, (Class<?>) ServicoUsuario.class);
      Injector.inject(controleDeAutenticacao0, (Class<?>) ControleDeAutenticacao.class, "servicoUsuario", (Object) servicoUsuario0);
      Injector.validateBean(controleDeAutenticacao0, (Class<?>) ControleDeAutenticacao.class);
      Injector.inject(controleDeProdutos0, (Class<?>) ControleDeProdutos.class, "controleDeAutenticacao", (Object) controleDeAutenticacao0);
      ServicoDeOperacao servicoDeOperacao0 = new ServicoDeOperacao();
      RepositorioDeOperacao repositorioDeOperacao0 = mock(RepositorioDeOperacao.class, new ViolatedAssumptionAnswer());
      Injector.inject(servicoDeOperacao0, (Class<?>) ServicoDeOperacao.class, "repositorioDeOperacao", (Object) repositorioDeOperacao0);
      Injector.validateBean(servicoDeOperacao0, (Class<?>) ServicoDeOperacao.class);
      Injector.inject(controleDeProdutos0, (Class<?>) ControleDeProdutos.class, "servicoDeOperacao", (Object) servicoDeOperacao0);
      ServicoDeProduto servicoDeProduto0 = new ServicoDeProduto();
      RepositorioDeProduto repositorioDeProduto0 = mock(RepositorioDeProduto.class, new ViolatedAssumptionAnswer());
      Injector.inject(servicoDeProduto0, (Class<?>) ServicoDeProduto.class, "repositorioDeProduto", (Object) repositorioDeProduto0);
      Injector.validateBean(servicoDeProduto0, (Class<?>) ServicoDeProduto.class);
      Injector.inject(controleDeProdutos0, (Class<?>) ControleDeProdutos.class, "servicoDeProduto", (Object) servicoDeProduto0);
      Injector.validateBean(controleDeProdutos0, (Class<?>) ControleDeProdutos.class);
      // Undeclared exception!
      try { 
        controleDeProdutos0.listarOperacoes("");
        fail("Expecting exception: RuntimeException");
      
      } catch(RuntimeException e) {
         //
         // Token inv\u00E1lido!
         //
         verifyException("almoxarifadovirtual.servidor.controle.ControleDeAutenticacao", e);
      }
  }

  @Test(timeout = 4000)
  public void test6()  throws Throwable  {
      ControleDeProdutos controleDeProdutos0 = new ControleDeProdutos();
      ControleDeAutenticacao controleDeAutenticacao0 = new ControleDeAutenticacao();
      ServicoLdap servicoLdap0 = new ServicoLdap();
      Injector.inject(controleDeAutenticacao0, (Class<?>) ControleDeAutenticacao.class, "servicoLdap", (Object) servicoLdap0);
      ServicoToken servicoToken0 = new ServicoToken();
      RepositorioDeToken repositorioDeToken0 = mock(RepositorioDeToken.class, new ViolatedAssumptionAnswer());
      doReturn((Token) null).when(repositorioDeToken0).findByChave(anyString());
      Injector.inject(servicoToken0, (Class<?>) ServicoToken.class, "repository", (Object) repositorioDeToken0);
      Injector.validateBean(servicoToken0, (Class<?>) ServicoToken.class);
      Injector.inject(controleDeAutenticacao0, (Class<?>) ControleDeAutenticacao.class, "servicoToken", (Object) servicoToken0);
      ServicoUsuario servicoUsuario0 = new ServicoUsuario();
      RepositorioDeUsuario repositorioDeUsuario0 = mock(RepositorioDeUsuario.class, new ViolatedAssumptionAnswer());
      Injector.inject(servicoUsuario0, (Class<?>) ServicoUsuario.class, "repositorio", (Object) repositorioDeUsuario0);
      Injector.validateBean(servicoUsuario0, (Class<?>) ServicoUsuario.class);
      Injector.inject(controleDeAutenticacao0, (Class<?>) ControleDeAutenticacao.class, "servicoUsuario", (Object) servicoUsuario0);
      Injector.validateBean(controleDeAutenticacao0, (Class<?>) ControleDeAutenticacao.class);
      Injector.inject(controleDeProdutos0, (Class<?>) ControleDeProdutos.class, "controleDeAutenticacao", (Object) controleDeAutenticacao0);
      ServicoDeOperacao servicoDeOperacao0 = new ServicoDeOperacao();
      RepositorioDeOperacao repositorioDeOperacao0 = mock(RepositorioDeOperacao.class, new ViolatedAssumptionAnswer());
      Injector.inject(servicoDeOperacao0, (Class<?>) ServicoDeOperacao.class, "repositorioDeOperacao", (Object) repositorioDeOperacao0);
      Injector.validateBean(servicoDeOperacao0, (Class<?>) ServicoDeOperacao.class);
      Injector.inject(controleDeProdutos0, (Class<?>) ControleDeProdutos.class, "servicoDeOperacao", (Object) servicoDeOperacao0);
      ServicoDeProduto servicoDeProduto0 = new ServicoDeProduto();
      RepositorioDeProduto repositorioDeProduto0 = mock(RepositorioDeProduto.class, new ViolatedAssumptionAnswer());
      Injector.inject(servicoDeProduto0, (Class<?>) ServicoDeProduto.class, "repositorioDeProduto", (Object) repositorioDeProduto0);
      Injector.validateBean(servicoDeProduto0, (Class<?>) ServicoDeProduto.class);
      Injector.inject(controleDeProdutos0, (Class<?>) ControleDeProdutos.class, "servicoDeProduto", (Object) servicoDeProduto0);
      Injector.validateBean(controleDeProdutos0, (Class<?>) ControleDeProdutos.class);
      Produto produto0 = new Produto();
      // Undeclared exception!
      try { 
        controleDeProdutos0.inserirProduto(produto0, "");
        fail("Expecting exception: RuntimeException");
      
      } catch(RuntimeException e) {
         //
         // Token inv\u00E1lido!
         //
         verifyException("almoxarifadovirtual.servidor.controle.ControleDeAutenticacao", e);
      }
  }

  @Test(timeout = 4000)
  public void test7()  throws Throwable  {
      ControleDeProdutos controleDeProdutos0 = new ControleDeProdutos();
      ControleDeAutenticacao controleDeAutenticacao0 = new ControleDeAutenticacao();
      ServicoLdap servicoLdap0 = new ServicoLdap();
      Injector.inject(controleDeAutenticacao0, (Class<?>) ControleDeAutenticacao.class, "servicoLdap", (Object) servicoLdap0);
      ServicoToken servicoToken0 = new ServicoToken();
      Token token0 = new Token();
      RepositorioDeToken repositorioDeToken0 = mock(RepositorioDeToken.class, new ViolatedAssumptionAnswer());
      doReturn(token0).when(repositorioDeToken0).findByChave(anyString());
      Injector.inject(servicoToken0, (Class<?>) ServicoToken.class, "repository", (Object) repositorioDeToken0);
      Injector.validateBean(servicoToken0, (Class<?>) ServicoToken.class);
      Injector.inject(controleDeAutenticacao0, (Class<?>) ControleDeAutenticacao.class, "servicoToken", (Object) servicoToken0);
      ServicoUsuario servicoUsuario0 = new ServicoUsuario();
      RepositorioDeUsuario repositorioDeUsuario0 = mock(RepositorioDeUsuario.class, new ViolatedAssumptionAnswer());
      Injector.inject(servicoUsuario0, (Class<?>) ServicoUsuario.class, "repositorio", (Object) repositorioDeUsuario0);
      Injector.validateBean(servicoUsuario0, (Class<?>) ServicoUsuario.class);
      Injector.inject(controleDeAutenticacao0, (Class<?>) ControleDeAutenticacao.class, "servicoUsuario", (Object) servicoUsuario0);
      Injector.validateBean(controleDeAutenticacao0, (Class<?>) ControleDeAutenticacao.class);
      Injector.inject(controleDeProdutos0, (Class<?>) ControleDeProdutos.class, "controleDeAutenticacao", (Object) controleDeAutenticacao0);
      ServicoDeOperacao servicoDeOperacao0 = new ServicoDeOperacao();
      RepositorioDeOperacao repositorioDeOperacao0 = mock(RepositorioDeOperacao.class, new ViolatedAssumptionAnswer());
      Injector.inject(servicoDeOperacao0, (Class<?>) ServicoDeOperacao.class, "repositorioDeOperacao", (Object) repositorioDeOperacao0);
      Injector.validateBean(servicoDeOperacao0, (Class<?>) ServicoDeOperacao.class);
      Injector.inject(controleDeProdutos0, (Class<?>) ControleDeProdutos.class, "servicoDeOperacao", (Object) servicoDeOperacao0);
      ServicoDeProduto servicoDeProduto0 = new ServicoDeProduto();
      RepositorioDeProduto repositorioDeProduto0 = mock(RepositorioDeProduto.class, new ViolatedAssumptionAnswer());
      Injector.inject(servicoDeProduto0, (Class<?>) ServicoDeProduto.class, "repositorioDeProduto", (Object) repositorioDeProduto0);
      Injector.validateBean(servicoDeProduto0, (Class<?>) ServicoDeProduto.class);
      Injector.inject(controleDeProdutos0, (Class<?>) ControleDeProdutos.class, "servicoDeProduto", (Object) servicoDeProduto0);
      Injector.validateBean(controleDeProdutos0, (Class<?>) ControleDeProdutos.class);
      Produto produto0 = new Produto();
      // Undeclared exception!
      try { 
        controleDeProdutos0.inserirProduto(produto0, "Reset Content");
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("almoxarifadovirtual.servidor.modelo.autenticacao.Token", e);
      }
  }

  @Test(timeout = 4000)
  public void test8()  throws Throwable  {
      ControleDeProdutos controleDeProdutos0 = new ControleDeProdutos();
      ControleDeAutenticacao controleDeAutenticacao0 = new ControleDeAutenticacao();
      ServicoLdap servicoLdap0 = new ServicoLdap();
      Injector.inject(controleDeAutenticacao0, (Class<?>) ControleDeAutenticacao.class, "servicoLdap", (Object) servicoLdap0);
      ServicoToken servicoToken0 = new ServicoToken();
      Token token0 = new Token();
      RepositorioDeToken repositorioDeToken0 = mock(RepositorioDeToken.class, new ViolatedAssumptionAnswer());
      doReturn(token0).when(repositorioDeToken0).findByChave(anyString());
      Injector.inject(servicoToken0, (Class<?>) ServicoToken.class, "repository", (Object) repositorioDeToken0);
      Injector.validateBean(servicoToken0, (Class<?>) ServicoToken.class);
      Injector.inject(controleDeAutenticacao0, (Class<?>) ControleDeAutenticacao.class, "servicoToken", (Object) servicoToken0);
      ServicoUsuario servicoUsuario0 = new ServicoUsuario();
      RepositorioDeUsuario repositorioDeUsuario0 = mock(RepositorioDeUsuario.class, new ViolatedAssumptionAnswer());
      Injector.inject(servicoUsuario0, (Class<?>) ServicoUsuario.class, "repositorio", (Object) repositorioDeUsuario0);
      Injector.validateBean(servicoUsuario0, (Class<?>) ServicoUsuario.class);
      Injector.inject(controleDeAutenticacao0, (Class<?>) ControleDeAutenticacao.class, "servicoUsuario", (Object) servicoUsuario0);
      Injector.validateBean(controleDeAutenticacao0, (Class<?>) ControleDeAutenticacao.class);
      Injector.inject(controleDeProdutos0, (Class<?>) ControleDeProdutos.class, "controleDeAutenticacao", (Object) controleDeAutenticacao0);
      ServicoDeOperacao servicoDeOperacao0 = new ServicoDeOperacao();
      RepositorioDeOperacao repositorioDeOperacao0 = mock(RepositorioDeOperacao.class, new ViolatedAssumptionAnswer());
      Injector.inject(servicoDeOperacao0, (Class<?>) ServicoDeOperacao.class, "repositorioDeOperacao", (Object) repositorioDeOperacao0);
      Injector.validateBean(servicoDeOperacao0, (Class<?>) ServicoDeOperacao.class);
      Injector.inject(controleDeProdutos0, (Class<?>) ControleDeProdutos.class, "servicoDeOperacao", (Object) servicoDeOperacao0);
      ServicoDeProduto servicoDeProduto0 = new ServicoDeProduto();
      RepositorioDeProduto repositorioDeProduto0 = mock(RepositorioDeProduto.class, new ViolatedAssumptionAnswer());
      Injector.inject(servicoDeProduto0, (Class<?>) ServicoDeProduto.class, "repositorioDeProduto", (Object) repositorioDeProduto0);
      Injector.validateBean(servicoDeProduto0, (Class<?>) ServicoDeProduto.class);
      Injector.inject(controleDeProdutos0, (Class<?>) ControleDeProdutos.class, "servicoDeProduto", (Object) servicoDeProduto0);
      Injector.validateBean(controleDeProdutos0, (Class<?>) ControleDeProdutos.class);
      // Undeclared exception!
      try { 
        controleDeProdutos0.encontrarProdutosPelaMarca("", "");
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("almoxarifadovirtual.servidor.modelo.autenticacao.Token", e);
      }
  }
}
