/*
 * This file was automatically generated by EvoSuite
 * Fri Mar 02 19:46:58 GMT 2018
 */

package almoxarifadovirtual.servidor.controle;

import org.junit.Test;
import static org.junit.Assert.*;
import almoxarifadovirtual.servidor.controle.Utils;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;
import org.springframework.http.ResponseEntity;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class Utils_ESTest extends Utils_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      ResponseEntity<Object> responseEntity0 = Utils.generateResponse((Object) null);
      assertEquals(200, responseEntity0.getStatusCodeValue());
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      Utils utils0 = new Utils();
      ResponseEntity<Object> responseEntity0 = Utils.generateResponse((Object) utils0);
      assertEquals(200, responseEntity0.getStatusCodeValue());
  }
}
