/*
 * This file was automatically generated by EvoSuite
 * Fri Mar 02 19:51:06 GMT 2018
 */

package almoxarifadovirtual.servidor.modelo.autenticacao;

import org.junit.Test;
import static org.junit.Assert.*;
import almoxarifadovirtual.servidor.modelo.autenticacao.Credenciais;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class Credenciais_ESTest extends Credenciais_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      Credenciais credenciais0 = new Credenciais();
      credenciais0.setSenha("");
      String string0 = credenciais0.getSenha();
      assertEquals("", string0);
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      Credenciais credenciais0 = new Credenciais();
      credenciais0.setLogin("l+");
      String string0 = credenciais0.getLogin();
      assertEquals("l+", string0);
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      Credenciais credenciais0 = new Credenciais();
      String string0 = credenciais0.getSenha();
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      Credenciais credenciais0 = new Credenciais();
      credenciais0.setLogin("");
      String string0 = credenciais0.getLogin();
      assertEquals("", string0);
  }

  @Test(timeout = 4000)
  public void test4()  throws Throwable  {
      Credenciais credenciais0 = new Credenciais();
      credenciais0.setSenha("*n[");
      String string0 = credenciais0.getSenha();
      assertEquals("*n[", string0);
  }

  @Test(timeout = 4000)
  public void test5()  throws Throwable  {
      Credenciais credenciais0 = new Credenciais();
      String string0 = credenciais0.getLogin();
      assertNull(string0);
  }
}
