/*
 * This file was automatically generated by EvoSuite
 * Fri Mar 02 19:36:45 GMT 2018
 */

package almoxarifadovirtual.servidor.servico;

import org.junit.Test;
import static org.junit.Assert.*;
import almoxarifadovirtual.servidor.servico.ServicoLdap;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class ServicoLdap_ESTest extends ServicoLdap_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      ServicoLdap servicoLdap0 = new ServicoLdap();
      boolean boolean0 = servicoLdap0.existeUsuario("Matteus");
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      ServicoLdap servicoLdap0 = new ServicoLdap();
      boolean boolean0 = servicoLdap0.existeUsuario("Mattevs");
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      ServicoLdap servicoLdap0 = new ServicoLdap();
      boolean boolean0 = servicoLdap0.validarUsuarioLdap("Matteus", "passwd-admin");
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      ServicoLdap servicoLdap0 = new ServicoLdap();
      boolean boolean0 = servicoLdap0.validarUsuarioLdap("Matteus", "passw]-admin");
      assertFalse(boolean0);
  }
}
