/*
 * This file was automatically generated by EvoSuite
 * Fri Mar 02 19:44:06 GMT 2018
 */

package almoxarifadovirtual.servidor.modelo.operacao;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import almoxarifadovirtual.servidor.modelo.operacao.TipoDeOperacao;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class TipoDeOperacao_ESTest extends TipoDeOperacao_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      TipoDeOperacao tipoDeOperacao0 = TipoDeOperacao.selecionarTipo("DEPOSITO");
      assertEquals(TipoDeOperacao.DEPOSITO, tipoDeOperacao0);
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      TipoDeOperacao[] tipoDeOperacaoArray0 = TipoDeOperacao.values();
      assertNotNull(tipoDeOperacaoArray0);
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      TipoDeOperacao tipoDeOperacao0 = TipoDeOperacao.valueOf("CADASTRO");
      assertEquals(TipoDeOperacao.CADASTRO, tipoDeOperacao0);
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      TipoDeOperacao tipoDeOperacao0 = TipoDeOperacao.selecionarTipo("retirada");
      assertEquals(TipoDeOperacao.RETIRADA, tipoDeOperacao0);
  }

  @Test(timeout = 4000)
  public void test4()  throws Throwable  {
      // Undeclared exception!
      try { 
        TipoDeOperacao.selecionarTipo("depnsito");
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // Funcao nao cadastrada no sistema depnsito, as fun\u00E7\u00F5es v\u00E1lidas s\u00E3o [CADASTRO, RETIRADA, DEPOSITO]
         //
         verifyException("almoxarifadovirtual.servidor.modelo.operacao.TipoDeOperacao", e);
      }
  }
}
